language: node_js
node_js:
  - "7"
install:
  - npm install
script: 
  - gulp compress
before_deploy:
  - pip install awscli --upgrade --user
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - aws s3 sync ./dist s3://$AWS_S3_PATH/$TRAVIS_BUILD_NUMBER
after_deploy:
  - gulp update-readme
  - cat README.md


