
language: node_js
node_js:
  - "7"
# This is needed to avoid building all the tags pushed by travis
branches:
  except:
    - /^v?\d+\.\d+\.\d+$/
before_install:
  # versioning: http://phdesign.com.au/programming/auto-increment-project-version-from-travis/
  # Create a git tag of the new version to use
  # If package.json major and minor versions match last tag, then increment last tag. Else use package.json major.minor.0.
  - "{ sed -nE 's/^[ \\t]*\"version\": \"([0-9]{1,}\\.[0-9]{1,}\\.)[0-9x]{1,}\",$/\\1/p' package.json; git describe --abbrev=0 --tags | sed -E 's/^v([0-9]{1,}\\.[0-9]{1,}\\.)([0-9]{1,})$/\\1 \\2/g'; } | tr \"\\n\" \" \" | awk '{printf($1==$2?\"v\"$2$3+1:\"v\"$1\"0\")}' | xargs -I {} git tag -a {} -m \"{}\"\n"
  # Update package.json based on the git tag we just created
  - npm --no-git-tag-version version from-git
  - VERSION=$(git describe --abbrev=0 --tags)
install:
  - npm install
script: 
  - gulp compress
before_deploy:
  - pip install awscli --upgrade --user
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - aws s3 sync ./dist s3://$AWS_S3_PATH/$VERSION
      - git remote add origin-pages https://${GH_TOKEN}@github.com/NachoColl/cognito.aws-sdk.js.git > /dev/null 2>&1
      - git push --tags
    on:
      branch: master
after_deploy:
  - gulp update-readme
  - cat README.md


