language: node_js
node_js:
  - "7"
install:
  - npm install
script: 
  - gulp compress
before_deploy:
  - pip install awscli --upgrade --user
deploy:
  skip_cleanup: true
  provider: script
  script:
    - aws s3 sync ./dist s3://$AWS_S3_PATH/$TRAVIS_BUILD_NUMBER


