language: node_js
node_js:
  - "7"
install:
before_script:
  - npm install
script: 
  - gulp compress
after_success:
  
before_deploy:
  - pip install awscli 
deploy:
  - aws s3 sync ./dist s3://$AWS_PATHTESTS/$TRAVIS_BUILD_NUMBER


