
language: node_js
node_js:
  - "7"
# This is needed to avoid building all the tags pushed by travis
branches:
  except:
    - /^v?\d+\.\d+\.\d+(\w*\W*)*$/
before_install:
  # If package.json version > git version (manually updated) we take that.
  - VN1=$(node -p "require('./package.json').version" | sed 's/[^0-9]*//g')
  - VN2=$(git describe --abbrev=0 --tags | sed 's/[^0-9]*//g')
  - NEW_VERSION=$(echo $VN1 $VN2 | awk '{ print($2>$1 ? $2 : $1)}' | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print})) 
  - cat $NEW_VERSION
  # Update package.json based on the git tag we just created.
  - git tag "$NEW_VERSION"
  - npm --no-git-tag-version version from-git
  - cat package.json
install:
  - npm install
script: 
  - gulp compress
  - gulp update-readme --version "$NEW_VERSION"
  - cat README.md
before_deploy:
  - pip install awscli --upgrade --user
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - aws s3 sync ./dist s3://$AWS_S3_PATH/$NEW_VERSION
  - provider: releases
    api_key: ${GH_TOKEN}
    overwrite: true
    skip_cleanup: true